### ISSUE TITLE
Changing Infohash from Unsupported Info-Fields

### ISSUE THREAD

**Issue by da2ce7** [torrust/torrust-index-backend#261]
Parent: https://github.com/torrust/torrust-index-backend/issues/275

Hi @da2ce7, I've been thinking about changing the infohash again, and I do not like the side effect. It has a similar effect to the "source" file. As we change the infohash:

- All the trackers listed on the torrent file are not going to work because the infohash has changed.
- Peer can only download the torrent from other peers using the same tracker.

What we are doing is kind of creating a new "normalized" torrent but somehow splitting the swarm.

In a public index/tracker, I think we should generate the same torrent, only adding the linked/associated tracker in the announce list.

_Originally posted by @josecelano in https://github.com/torrust/torrust-index-backend/issues/260#issuecomment-1692357442_

**Comment by josecelano** [comment]
Hi @da2ce7, I'm working on a sample application to import torrents from an external source into the Torrust Index.

Repo: https://github.com/torrust/academic-torrents-importer (still private).

The process is:

1. Check if the torrent already exists in the Index using the API and the **current** infohash
2. Upload the torrent if it does not exist.

As the info-hash might change if I retry the request, the script is going to try to upload the same torrent again because checking whether the torrent exists or not will return a Not Found 404 (because we are using the original infohash).

I'm using the API endpoint `GET /v1/torrent/{info_hash}` to check if the torrent exists. I would need to check if a torrent with a given original info-hash exists (not the new info-hash). Currently, that's not possible either with the search or torrent details endpoint.

If we decide to continue changing the info-hash after uploading, we should provide a way for clients to know if a torrent with an original info-hash was already uploaded. It should tell clients the current info-hash for the torrent. Otherwise, we force people who want to migrate torrents to our Index to track info-hash changes, making migration tools more complex. And I think we should make migrating torrents from other indexes as easy as possible. For the time being, I'm going to re-upload the torrent and do not make the migration tool fail if the torrent already exists (current behavior), but that's an expensive action in comparison to just checking if the original info-hash was already uploaded with a current or new endpoint.
