### ISSUE TITLE
Add endpoint for image proxying

### ISSUE THREAD

**Issue by WarmBeer** [torrust/torrust-index-backend#91]
Torrent descriptions can contain externally hosted images. 

To preserve our users' privacy, we should load external images through a proxy.

**Comment by WarmBeer** [comment]
Hey @josecelano, @da2ce7 

I was thinking of adding an image cache to the backend and a public API endpoint that takes a direct image URL as an urlencoded GET parameter. The API endpoint to be called `/imageproxy` would then fetch the image from the `?url` GET parameter on request, then save it in a cache and serve it back to the client. 

Example:

We have an `<img>` on the frontend with `src="https://en.wikipedia.org/wiki/Test_card#/media/File:SMPTE_Color_Bars.svg"`. This is an external source, so we are going to load the image using the backend's `/imageproxy` endpoint.

To pass the image src as a `GET` parameter, we would first have to url encode it: `https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FTest_card%23%2Fmedia%2FFile%3ASMPTE_Color_Bars.svg`.

We then substitute the img src with the imageproxy link: `src="https://api.torrust.com/imageproxy?url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FTest_card%23%2Fmedia%2FFile%3ASMPTE_Color_Bars.svg"`.

This should then display the original image, but through our proxy.

What do you think of this approach?

**Comment by josecelano** [comment]
Hi @WarmBeer, as we discussed, I see these prons and cons:

### Prons

- We do not need to handle media uploads.
- We do not need to keep the images. The cache will be filled again as users use the application. That makes the deployment simpler, although we need a storage anyway for other things like the SQLite database.

### Cons

- It could be slow the first time we serve the image because we have to get it from the original location.
- It could be inefficient because we need to get the image again when the cache expires. We need to check again that the image is an actual image.
- The original image link could be broken (something we have to warn users about).

### Notes

- Check that the image is an actual image (not only with the `content-type: image/png` header).
- Use a two-level cache: memory and disk. For the time being, we can only use disk cache.
- Allow the browser to cache the image (with the right response header). WE can use versioning to update the image if the original image changes, but I do not think we need that now.

**Comment by da2ce7** [comment]
[IndexMap](https://docs.rs/indexmap/latest/indexmap/index.html) could be very good for a in-memory cache.  You can set the max-items of the cache, and insert/pop items once it reaches the desired file.  (This works if the cache has some limitations of the size of the items).
